project:
  type: website

website:
  title: "Annaïg De Walsche"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: bibliographie.qmd
        text: Research

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

